// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parcial2_Levid.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 2000f,
                            Descripcion = "Mani",
                            Existencia = 200,
                            Precio = 2600f
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 3000f,
                            Descripcion = "Pistachos",
                            Existencia = 400,
                            Precio = 3600f
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 1500f,
                            Descripcion = "Pasas",
                            Existencia = 100,
                            Precio = 2000f
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 4000f,
                            Descripcion = "Ciruela",
                            Existencia = 700,
                            Precio = 5600f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
